{
 "title": "Environment",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "WITH range AS (\n  SELECT\n    $__timeFrom()::timestamptz AS from_time,\n    $__timeTo()::timestamptz AS to_time\n),\nbucket AS (\n  SELECT CASE\n    WHEN to_time - from_time <= interval '48 hour' THEN '1 minute'\n    WHEN to_time - from_time <= interval '4 days' THEN '5 minutes'\n    WHEN to_time - from_time <= interval '8 days' THEN '10 minutes'\n    WHEN to_time - from_time <= interval '15 days' THEN '30 minutes'\n    ELSE '1 hour'\n  END::interval AS interval\n  FROM range\n),\ndevices AS (\n  SELECT DISTINCT du_id FROM monitoring.antennas\n),\nbuckets AS (\n  SELECT DISTINCT time_bucket((SELECT interval FROM bucket), datetime) AS bucket_time\n  FROM monitoring.mesures\n  WHERE datetime BETWEEN (SELECT from_time FROM range) AND (SELECT to_time FROM range)\n),\ncombined AS (\n  SELECT b.bucket_time AS time, d.du_id\n  FROM buckets b\n  CROSS JOIN devices d\n)\nSELECT\n  c.time,\n  c.du_id,\n  ROUND(AVG(m.temperature)::numeric, 2) AS temperature\nFROM combined c\nLEFT JOIN monitoring.mesures m\n  ON m.du_id = c.du_id\n  AND time_bucket((SELECT interval FROM bucket), m.datetime) = c.time\nGROUP BY c.time, c.du_id\nORDER BY c.time, c.du_id;\n\n\n/*WITH range AS (\n  SELECT\n    $__timeFrom()::timestamptz AS from_time,\n    $__timeTo()::timestamptz AS to_time\n),\nbucket AS (\n  SELECT CASE\n    WHEN to_time - from_time <= interval '6 hour' THEN '1 minute'\n    WHEN to_time - from_time <= interval '24 hours' THEN '5 minutes'\n    WHEN to_time - from_time <= interval '7 days' THEN '10 minutes'\n    WHEN to_time - from_time <= interval '15 days' THEN '30 minutes'\n    ELSE '1 hours'\n  END AS interval\n  FROM range\n)\nSELECT\n  time_bucket(bucket.interval::interval, m.datetime)::timestamptz AS time, \n  m.du_id,\n  AVG(m.temperature) AS temperature\nFROM monitoring.mesures m\nJOIN bucket ON TRUE\nWHERE $__timeFilter(m.datetime)\nGROUP BY time, m.du_id\nORDER BY time, m.du_id;\n*/\n\n"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "WITH range AS (\n  SELECT\n    $__timeFrom()::timestamptz AS from_time,\n    $__timeTo()::timestamptz AS to_time\n),\nbucket AS (\n  SELECT CASE\n    WHEN to_time - from_time <= interval '48 hour' THEN '1 minute'\n    WHEN to_time - from_time <= interval '4 days' THEN '5 minutes'\n    WHEN to_time - from_time <= interval '8 days' THEN '10 minutes'\n    WHEN to_time - from_time <= interval '15 days' THEN '30 minutes'\n    ELSE '1 hour'\n  END::interval AS interval\n  FROM range\n),\ndevices AS (\n  SELECT DISTINCT du_id FROM monitoring.antennas\n),\nbuckets AS (\n  SELECT DISTINCT time_bucket((SELECT interval FROM bucket), datetime) AS bucket_time\n  FROM monitoring.mesures\n  WHERE datetime BETWEEN (SELECT from_time FROM range) AND (SELECT to_time FROM range)\n),\ncombined AS (\n  SELECT b.bucket_time AS time, d.du_id\n  FROM buckets b\n  CROSS JOIN devices d\n)\nSELECT\n  c.time,\n  c.du_id,\n  ROUND(AVG(m.voltage)::numeric, 2) AS voltage\nFROM combined c\nLEFT JOIN monitoring.mesures m\n  ON m.du_id = c.du_id\n  AND time_bucket((SELECT interval FROM bucket), m.datetime) = c.time\nGROUP BY c.time, c.du_id\nORDER BY c.time, c.du_id;\n/*\nSELECT\n  time_bucket(bucket.interval::interval, m.datetime) AS time,\n  m.du_id,\n  AVG(m.voltage) AS voltage\nFROM monitoring.mesures m\nJOIN bucket ON TRUE\nWHERE $__timeFilter(m.datetime)\nGROUP BY time, m.du_id\nORDER BY time, m.du_id;\n*/"
    }
   ]
  },
  {
   "title": "Number of up DUs (by hour)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH time_series AS (\n  SELECT generate_series(\n    date_trunc('hour', $__timeFrom()::timestamptz),\n    date_trunc('hour', $__timeTo()::timestamptz),\n    interval '1 hour'\n  ) AS time\n),\nactive_counts AS (\n  SELECT\n    time_bucket('1 hour', m.datetime) AS time,\n    COUNT(DISTINCT du_id) AS du_count\n  FROM monitoring.mesures m\n  WHERE $__timeFilter(m.datetime)\n  GROUP BY time\n)\nSELECT\n  ts.time,\n  COALESCE(ac.du_count, 0) AS count\nFROM time_series ts\nLEFT JOIN active_counts ac ON ts.time = ac.time\nORDER BY ts.time;\n"
    }
   ]
  },
  {
   "title": "uptime percentage (over 5mn bins)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH params AS (\n  SELECT \n    date_trunc('minute', $__timeFrom()::timestamptz)  AS start_time, \n    date_trunc('minute', $__timeTo()::timestamptz) AS end_time\n),\nup_minutes AS (\n  SELECT \n    (1 + EXTRACT(EPOCH FROM (p.end_time - p.start_time)) / 60) AS minutes_diff\n  FROM params p\n),\ndevices AS (\n  SELECT DISTINCT du_id \n  FROM monitoring.antennas\n),\ndata as (SELECT\n  d.du_id, \n  time_bucket('5 minutes', m.datetime) ,\n  (CASE WHEN COUNT(temperature) IS NOT NULL THEN CASE WHEN COUNT(temperature) > 0 THEN 5 ELSE 0 END ELSE 0 END) AS t_up\nFROM devices d LEFT OUTER JOIN monitoring.mesures m on d.du_id=m.du_id and $__timeFilter(datetime)\nGROUP BY time_bucket,d.du_id\nORDER BY d.du_id)\n\nSELECT\n  d.du_id,\n  100 * LEAST(SUM(d.t_up),u.minutes_diff::bigint) / u.minutes_diff AS uptime_percentage\nFROM data d\nCROSS JOIN up_minutes u\nGROUP BY d.du_id,u.minutes_diff\nORDER BY d.du_id, uptime_percentage;\n\n/*\nWITH params AS (\n  SELECT \n    date_trunc('minute', $__timeFrom()::timestamptz)  AS start_time, \n    date_trunc('minute', $__timeTo()::timestamptz) AS end_time\n),\nup_minutes AS (\n  SELECT \n    (1 + EXTRACT(EPOCH FROM (p.end_time - p.start_time)) / 60) AS minutes_diff\n  FROM params p\n),\ndevices AS (\n  SELECT DISTINCT du_id \n  FROM monitoring.mesures\n)\n\nSELECT\n  d.du_id,\n  100 * COUNT(m.temperature) / u.minutes_diff AS uptime_percentage\nFROM devices d\nCROSS JOIN params p\nCROSS JOIN up_minutes u\nLEFT JOIN monitoring.mesures m \n  ON d.du_id = m.du_id\n  AND m.datetime BETWEEN p.start_time AND p.end_time\nGROUP BY d.du_id, u.minutes_diff\nORDER BY d.du_id, uptime_percentage;\n\n*/\n/*\nSELECT du as du_id, uptime_percentage\nFROM monitoring.device_uptime_in_range_all($__timeFrom()::timestamptz,$__timeTo()::timestamptz)\nORDER BY du_id\n*/\n/*\nWITH params AS (\n  SELECT \n    $__timeFrom()::timestamp AS start_time, \n    $__timeTo()::timestamp AS end_time\n),\ntotal_minutes AS (\n  SELECT \n    EXTRACT(EPOCH FROM (end_time - start_time)) / 60 AS total_minutes\n  FROM params\n),\ndevices AS (\n  SELECT DISTINCT du_id \n  FROM mesures\n  \n),\nup_minutes AS (\n  SELECT \n    du_id,\n    COUNT(*) AS count\n  FROM mesures, params\n  WHERE \n    datetime >= params.start_time AND \n    datetime < params.end_time\n  GROUP BY du_id\n)\nSELECT\n  d.du_id,\n  COALESCE(u.count, 0) AS up_minutes,\n  t.total_minutes,\n  CASE \n    WHEN t.total_minutes > 0 \n      THEN (COALESCE(u.count, 0) * 100.0) / t.total_minutes \n    ELSE 0 \n  END AS uptime_percentage\nFROM devices d\nCROSS JOIN total_minutes t\nLEFT JOIN up_minutes u ON d.du_id = u.du_id\nORDER BY uptime_percentage, d.du_id;\n*/"
    }
   ]
  },
  {
   "title": "Effective data taking percentage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH params AS (\n  SELECT \n    date_trunc('minute', $__timeFrom()::timestamptz)  AS start_time, \n    date_trunc('minute', $__timeTo()::timestamptz) AS end_time\n),\nup_minutes AS (\n  SELECT \n    (EXTRACT(EPOCH FROM (p.end_time - p.start_time)) / 60) AS minutes_diff\n  FROM params p\n),\ndevices AS (\n  SELECT DISTINCT du_id \n  FROM monitoring.antennas\n),\ndata as (SELECT\n  d.du_id, \n  m.datetime,\n  (CASE WHEN COUNT(temperature) IS NOT NULL THEN CASE WHEN COUNT(temperature) > 0 THEN 1 ELSE 0 END ELSE 0 END) AS t_up\nFROM devices d LEFT OUTER JOIN monitoring.mesures m on d.du_id=m.du_id and $__timeFilter(datetime)\nGROUP BY m.datetime, d.du_id\nORDER BY d.du_id)\n\nSELECT\n  d.du_id,\n  100 * LEAST(SUM(d.t_up),u.minutes_diff::bigint) / u.minutes_diff AS uptime_percentage\nFROM data d\nCROSS JOIN up_minutes u\nGROUP BY d.du_id,u.minutes_diff\nORDER BY d.du_id, uptime_percentage;"
    }
   ]
  }
 ]
}